baseurl = "http://jiajasper.github.io"
languageCode = "en-us"
title = "Jasper x Jia"
theme = "mediumish-gohugo-theme"

enableEmoji = true
themesDir = "themes/"
paginate = 18

[params]
  description ="Jasper's Portfolio"

[params.index]
  picture = "/images/instagram_dp.png"
  title = "Jasper Jia"
  subtitle = "Innovation Design Engineering Student based in London/Melbourne"

[params.author]
  name = "Jasper Jia"
  thumbnail = "/images/instagram_dp.png"
  description = "yo!"

[params.social]
  github = "jiajasper"
  linkedin = "jasperjia"
  instagram = "jasperfool"

  ## Main Menu
[[menu.main]]
    name = "Project"
    weight = 100
    identifier = "project"
    url = "/project"
[[menu.main]]
    name = "Bio"
    identifier = "about"
    weight = 200
    url = "/static"
