baseURL = "https://jiajasper.github.io/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Jasper Jia"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"

[menu]
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 1


    [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Projects"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 2


# Home page config
      [languages.en.params.home]
        # amount of RSS pages
        rss = 10
        # Home page profile
        [languages.en.params.home.profile]
          enable = true
          # Gravatar Email for preferred avatar in home page
          gravatarEmail = ""
          # URL of avatar shown in home page
          avatarURL = "/images/instagram_dp.png"
          # title shown in home page (HTML format is supported)
          title = "Jasper Jia"
          # subtitle shown in home page
          subtitle = "Designer, Developer based in London/Melbourne"
          # whether to use typeit animation for subtitle
          typeit = true
          # whether to show social links
          social = true
          # disclaimer (HTML format is supported)
          disclaimer = ""

        # Home page posts
        [languages.en.params.home.posts]
          enable = false
          # special amount of posts in each home posts page
          paginate = 6

 # Social config in home page
      [languages.en.params.social]
        GitHub = "jasperxjia"
        Linkedin = "jasperjia"
        Instagram = "jasperfool"

  # Footer config
  [params.footer]
    enable = true
    # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
    custom = 'Jasper @2020'
    # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
    hugo = false
    # LoveIt NEW | 0.2.0 whether to show copyright info
    copyright = false
    # LoveIt NEW | 0.2.0 whether to show the author
    author = false

